import type { Metadata } from "next";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import { Notifications } from "@mantine/notifications";
import "./globals.css";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/notifications/styles.css";

import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { emotionTransform, MantineEmotionProvider } from "@mantine/emotion";
import { RootStyleRegistry } from "./EmotionRootStyleRegistry";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <UserProvider>
          <RootStyleRegistry>
            <MantineEmotionProvider>
              <MantineProvider stylesTransform={emotionTransform}>
                <Notifications />
                {children}
              </MantineProvider>
            </MantineEmotionProvider>
          </RootStyleRegistry>
        </UserProvider>
      </body>
    </html>
  );
}
